ARG IMAGE_BASE

FROM ${IMAGE_BASE}

ARG NGINX_VERSION

WORKDIR /tmp

RUN \
# packages
	apk update \
	&& apk add --update --no-cache apache2-utils \
		autoconf \
		automake \
		bash \
		bind-tools \
		expat-dev \
		clang \
		clang-extra-tools=7.0.1-1 \
		curl \
		diffutils \
		expect \
		gcc \
		g++ \
		gd \
		gdb \
		geoip-dev \
		git \
		gzip \
		jq \
		libev-dev \
		libxml2-dev \
		libxslt-dev \
		make \
		mandoc \
		openssl \
		openssl-dev \
		patch \
		pcre-dev \
		perl \
		perl-app-cpanminus \
		perl-libwww \
		perl-list-moreutils \
		perl-utils \
		procps \
		python2 \
		tar \
		unbound \
		valgrind \
		wget \
		which \
		zlib-dev \
# weighttp
	&& curl -L https://github.com/lighttpd/weighttp/archive/weighttp-0.4.tar.gz -o weighttp.tar.gz \
	&& mkdir -p /tmp/weighttp \
	&& cd /tmp/weighttp \
	&& tar -xzvf /tmp/weighttp.tar.gz --strip-components 1 \
	&& ./waf configure \
	&& ./waf build \
	&& ./waf install \
	&& cd /tmp \
# perl modules
	&& cpanm --force \
		Spiffy \
		Test::Base \
		Test::Nginx \
		JSON \
# unbound
	&& touch /run/unbound.control.sock \
	&& unbound-control-setup \
# nginx
	&& curl -L http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz -o nginx.tar.gz \
	&& mkdir -p /src/nginx \
	&& cd /src/nginx \
	&& tar -xzvf /tmp/nginx.tar.gz --strip-components 1 \
	&& ./configure \
	&& cd /tmp \
# nginx no pool patches
	&& curl -L https://github.com/openresty/no-pool-nginx/archive/master.tar.gz -o no-pool-nginx.tar.gz \
	&& mkdir -p /src/patches/no-pool-nginx \
	&& cd /src/patches/no-pool-nginx \
	&& tar -xzvf /tmp/no-pool-nginx.tar.gz --strip-components 1 \
	&& cd /tmp \
# cleanup
	&& rm -rf ./*

COPY unbound.conf /etc/unbound/unbound.conf
COPY unbound_local_zone.conf /etc/unbound/unbound_local_zone.conf

WORKDIR /
