ARG IMAGE_BASE

FROM ${IMAGE_BASE}

ARG NGINX_VERSION

WORKDIR /tmp

RUN \
# packages
	apk update \
	&& apk add --no-cache \
		apache2-utils=2.4.53-r0 \
		autoconf=2.69-r2 \
		automake=1.16.2-r0 \
		bash=5.0.17-r0 \
		bind-tools=9.16.27-r1 \
		clang=10.0.0-r2 \
		clang-extra-tools=10.0.0-r2 \
		curl=7.79.1-r1 \
		diffutils=3.7-r0 \
		expat-dev=2.2.10-r4 \
		expect=5.45.4-r0 \
		g++=9.3.0-r2 \
		gcc=9.3.0-r2 \
		gdb=9.2-r0 \
		git=2.26.3-r1 \
		gzip=1.12-r0 \
		jq=1.6-r1 \
		libev-dev=4.33-r0 \
		libxml2-dev=2.9.14-r0 \
		make=4.3-r0 \
		openssl=1.1.1o-r0 \
		openssl-dev=1.1.1o-r0 \
		patch=2.7.6-r7 \
		pcre-dev=8.44-r0 \
		perl=5.30.3-r0 \
		perl-app-cpanminus=1.7045-r0 \
		perl-libwww=6.44-r0 \
		perl-list-moreutils=0.428-r0 \
		perl-utils=5.30.3-r0 \
		procps=3.3.16-r0 \
		python2=2.7.18-r0 \
		tar=1.32-r2 \
		unbound=1.10.1-r0 \
		valgrind=3.15.0-r1 \
		wget=1.20.3-r1 \
		which=2.21-r1 \
		zlib-dev=1.2.12-r1 \
# weighttp
	&& curl -L https://github.com/lighttpd/weighttp/archive/weighttp-0.4.tar.gz -o weighttp.tar.gz \
	&& mkdir -p /tmp/weighttp \
	&& cd /tmp/weighttp \
	&& tar -xzvf /tmp/weighttp.tar.gz --strip-components 1 \
	&& ./waf configure \
	&& ./waf build \
	&& ./waf install \
	&& cd /tmp \
# perl modules
	&& cpanm --force \
		INGY/Spiffy-0.46.tar.gz \
		INGY/Test-Base-0.89.tar.gz \
		AGENT/Test-Nginx-0.29.tar.gz \
		ISHIGAKI/JSON-4.06.tar.gz \
# unbound
	&& touch /run/unbound.control.sock \
	&& unbound-control-setup \
# nginx
	&& curl -L http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz -o nginx.tar.gz \
	&& mkdir -p /src/nginx \
	&& cd /src/nginx \
	&& tar -xzvf /tmp/nginx.tar.gz --strip-components 1 \
	&& ./configure \
	&& cd /tmp \
# nginx no pool patches
	&& curl -L https://github.com/openresty/no-pool-nginx/archive/master.tar.gz -o no-pool-nginx.tar.gz \
	&& mkdir -p /src/patches/no-pool-nginx \
	&& cd /src/patches/no-pool-nginx \
	&& tar -xzvf /tmp/no-pool-nginx.tar.gz --strip-components 1 \
	&& cd /tmp \
# cleanup
	&& rm -rf ./*

COPY unbound.conf /etc/unbound/unbound.conf
COPY unbound_local_zone.conf /etc/unbound/unbound_local_zone.conf

WORKDIR /
