name: Docker

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:

env:
  IMAGE_NAME: nginx-module-toolbox

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    strategy:
      matrix:
        imgbase:
          - alpine:3.12.0
          - amazonlinux:2.0.20200722.0
          - ubuntu:focal-20200925
        nginx:
          - 1.10.3
          - 1.12.2
          - 1.14.2
          - 1.16.1
          - 1.18.0
          - 1.20.2
          - 1.22.0
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          IMAGE_BASE=${{ matrix.imgbase }}
          docker build . --file Dockerfile.${IMAGE_BASE%%:*} --tag image --build-arg IMAGE_BASE=${{ matrix.imgbase }} --build-arg NGINX_VERSION=${{ matrix.nginx }}
      - name: Log into Docker Hub registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.hub.docker.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push image Docker Hub registry
        run: |
          IMAGE_ID=registry.hub.docker.com/${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')
          echo IMAGE_ID=${IMAGE_ID}
          echo VERSION=${VERSION}
          IMAGE_BASE=${{ matrix.imgbase }}
          IMAGE_FULL_NAME=${IMAGE_ID}:${IMAGE_BASE/:/-}-${{ matrix.nginx }}-${VERSION}
          docker tag image ${IMAGE_FULL_NAME}
          docker push ${IMAGE_FULL_NAME}
      - name: Log into GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Push image GitHub registry
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')
          echo IMAGE_ID=${IMAGE_ID}
          echo VERSION=${VERSION}
          IMAGE_BASE=${{ matrix.imgbase }}
          IMAGE_FULL_NAME=${IMAGE_ID}:${IMAGE_BASE/:/-}-${{ matrix.nginx }}-${VERSION}
          docker tag image ${IMAGE_FULL_NAME}
          docker push ${IMAGE_FULL_NAME}
